---
title: "Integrated serosurveillance to assess disease elimination in coastal Ecuador"
subtitle: "Summarize IgG distributions for each antigen"
author: "Lesly Simbaña, Ben Arnold ben.arnold@ucsf.edu"
date: "updated: `r Sys.time()`"
format:
  html:
    
    toc: true
    embed-resources: true
    code-fold: true
    link-external-newwindow: true
---

# Summary

Create histograms of IgG levels to trachoma, oncho, yaws, and cholera antigens

# Preamble

```{r preamble}
library(here)
here()
#----------------------------
# source the config file
#----------------------------
source(here("R","0-config.R"))

```

# Load the Luminex IgG data

```{r load antibody data}
#-------------------------------
# load the formatted MBA data
# for EcoMID, created by
# 0-all_sero_results_dataclean.Rmd
#
# data are in long format
#-------------------------------
d <- read_rds(here("~/Library/CloudStorage/Box-Box/EcoMid/data/serology/final/ecomid_serology_datasets","ecomid_sero_antigen_seropos_long_2025-12-18.rds"))


#-------------------------------
# filter to relevant antigens
# relevel antigen labels for
# plotting in order
#-------------------------------
d1 <- d %>%
  filter(antigen %in% c("pgp3","ct694","rp17","tmpa","ov16")) %>%
  mutate(antigen_plot = antigen_lab,
         antigen_plot = factor(antigen_plot, levels=c("C. trachomatis Pgp3","C. trachomatis CT694","T. palladium rp17","T. palladium tmpa","O. volvulus Ov16")))
```


# Create histograms of IgG values

```{r distributions of igg}



# custom log labels
log10labs <- c( 
  expression(10^0),
  expression(10^1),
  expression(10^2),
  expression(10^3),
  expression(10^4),
  expression(10^5)
)

# mfi cutoffs
d_mficut <- d1 %>% 
  group_by(antigen_plot) %>%
  select(antigen_plot, mficut) %>%
  distinct() %>%
  mutate(log10mficut = log10(mficut))

plot_igg_dists <- ggplot(data=d1, aes(x=log10mfi)) + 
  facet_wrap(.~ antigen_plot,ncol=2, scales = "free_y") +
  geom_histogram(binwidth = 0.1, fill = "deepskyblue4",color = NA, alpha=1) + 
  geom_vline(data=d_mficut, aes(xintercept = log10mficut),color="gray30",linetype="dashed") + 
  scale_x_continuous(breaks = 0:5, labels = log10labs) +
  coord_cartesian(xlim=c(0,5)) + 
  labs(x="Luminex IgG response (MFI-bg)",y="Number of samples") +
  theme_classic()
  


plot_igg_dists

ggsave(filename = here("output","ecomid_igg_distributions.png"),plot_igg_dists, device = "png",height = 150,width=120, units = "mm")

```


# Session Info
```{r session info}
sessionInfo()
```


